name: Utils
version: '1.0-SNAPSHOT'
main: morey.utils.Main
api-version: 1.18
author: morey
description: A plugin with some useful commands
commands:
  1:
    description: Gamemode command
    permission-message: "§c§l(!) §cYou don't have access to this command."
    permission: admin.gamemode
  2:
    description: Gamemode command
    permission-message: "§c§l(!) §cYou don't have access to this command."
    permission: admin.gamemode
  3:
    description: Gamemode command
    permission-message: "§c§l(!) §cYou don't have access to this command."
    permission: admin.gamemode
  0:
    description: Gamemode command
    permission-message: "§c§l(!) §cYou don't have access to this command."
    permission: admin.gamemode
  speed:
    description: Speed command
    permission-message: "§c§l(!) §cYou don't have access to this command."
    permission: admin.speed
  v:
    description: Vanish command
    permission-message: "§c§l(!) §cYou don't have access to this command."
    permission: admin.vanish
  bc:
    description: Broadcast command
    permission-message: "§c§l(!) §cYou don't have access to this command."
    permission: admin.broadcast
  de:
    description: Debug command
    permission-message: "§c§l(!) §cYou don't have access to this command."
    permission: admin.debug
  whois:
    description: Whois command
    permission-message: "§c§l(!) §cYou don't have access to this command."
    permission: admin.whois
  rl:
    description: Reload command
    permission-message: "§c§l(!) §cYou don't have access to this command."
    permission: admin.reload
  ping:
    description: Ping command
    permission-message: "§c§l(!) §cYou don't have access to this command."
    permission: admin.ping
  msg:
    description: Message command
    permission-message: "§c§l(!) §cYou don't have access to this command."
    permission: admin.msg
  r:
    description: Reply command
    permission-message: "§c§l(!) §cYou don't have access to this command."
    permission: admin.reply
  tell:
    description: Tell command
    permission-message: "§c§l(!) §cYou don't have access to this command."
    permission: admin.tell
  m:
    description: Message command
    permission-message: "§c§l(!) §cYou don't have access to this command."
    permission: admin.m
  w:
    description: Message command
    permission-message: "§c§l(!) §cYou don't have access to this command."
    permission: admin.w
  whisper:
    description: Message command
    permission-message: "§c§l(!) §cYou don't have access to this command."
    permission: admin.whisper